# Блок 4. Построение ML моделей

## Описание блока:
В данном блоке будут обучены ML модели с применением кросс валидации и подбора лучших гиперпараметров. Подробное текстовое описания получившегося результата будет в  [Открыть тетрадку "Part 0"](Part%200.%20Research%20results.ipynb)

In [1]:
# импорт основных библиотек блока
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import optuna
from functools import partial
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from all_functions.datasets_load import load_all_datasets
from all_functions.datasets_transfom import *
from all_functions.func_for_ml import *

/home/danila/mainpk/masters_work/Project_Financial_assets_and_ML/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# фиксация сида на будущее
RANDOM_STATE = 654321

In [3]:
# загрузка датасетов
crypt_Ethereum, crypt_BTC, futures_Brent_LCOK5, \
futures_WTI_CLJ5, share_metal_jiangxi_copper, \
share_metal_baoshan_iron, share_oil_petrochina_hk, \
share_oil_equinor_oslo, spot_preciouse_metal_AG, spot_preciouse_metal_AU = load_all_datasets()

In [4]:
# трансформация датасетов
crypt_Ethereum = transform_data(crypt_Ethereum)
crypt_BTC = transform_data(crypt_BTC)

futures_WTI_CLJ5 = transform_data(futures_WTI_CLJ5)
futures_Brent_LCOK5 = transform_data(futures_Brent_LCOK5)

share_metal_jiangxi_copper  = transform_data(share_metal_jiangxi_copper)
share_metal_baoshan_iron  = transform_data(share_metal_baoshan_iron)

share_oil_petrochina_hk  = transform_data(share_oil_petrochina_hk)
share_oil_equinor_oslo  = transform_data(share_oil_equinor_oslo)

spot_preciouse_metal_AU  = transform_data(spot_preciouse_metal_AU)
spot_preciouse_metal_AG = transform_data(spot_preciouse_metal_AG)

## Построение ML моделей

In [5]:
all_data = {'crypt_Ethereum': crypt_Ethereum, 
 'crypt_BTC':crypt_BTC,
 'futures_Brent_LCOK5':futures_Brent_LCOK5,
'futures_WTI_CLJ5': futures_WTI_CLJ5,
'share_metal_jiangxi_copper': share_metal_jiangxi_copper, 
'share_metal_baoshan_iron': share_metal_baoshan_iron,
 'share_oil_petrochina_hk': share_oil_petrochina_hk, 
'share_oil_equinor_oslo': share_oil_equinor_oslo,
 'spot_preciouse_metal_AG': spot_preciouse_metal_AG,
 'spot_preciouse_metal_AU': spot_preciouse_metal_AU}

In [6]:
# Создание датасета для записи результатов обучения
all_reault = pd.DataFrame()

name_ds = []
for i, _ in all_data.items():
    name_ds.append(i)
all_reault['dataset_name'] = name_ds

# фиксация в общем датасете средней цены, для наглядности диапазона цен

mean_ds = []
for i, n in all_data.items():
    mean_ds.append(n.mean()['Цена'])
all_reault['dataset_mean_price'] = mean_ds

all_reault

                 dataset_name  dataset_mean_price
0              crypt_Ethereum         1264.224518
1                   crypt_BTC        24007.290015
2         futures_Brent_LCOK5           68.036667
3            futures_WTI_CLJ5           63.524965
4  share_metal_jiangxi_copper           10.239784
5    share_metal_baoshan_iron            5.255690
6     share_oil_petrochina_hk            3.622050
7      share_oil_equinor_oslo          187.087574
8     spot_preciouse_metal_AG           20.814301
9     spot_preciouse_metal_AU         1677.948521

In [7]:
def objective_RFregresson(trial, data):
    
    # --- Гиперпараметры для Random Forest ---
    n_estimators = trial.suggest_int("n_estimators", 50, 300)
    max_depth = trial.suggest_int("max_depth", 3, 20)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 5)
    max_features = trial.suggest_categorical("max_features", ["sqrt", "log2"])

    # --- Разделение данных ---
    train_raw, valid_raw, _ = split_data(data)
    tail_len = 30

    train = upgrade_dataset(train_raw)
    valid_with_tail = pd.concat([train_raw.tail(tail_len), valid_raw])
    valid_with_tail = upgrade_dataset(valid_with_tail)
    valid = valid_with_tail.loc[valid_raw.index]

    X_train, y_train = return_x_y(train)
    X_valid, y_valid = return_x_y(valid)

    # --- Модель ---
    model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)
    y_pred = model.predict(X_valid)

    rmse = np.sqrt(mean_squared_error(y_valid, y_pred))
    return rmse

In [8]:
%%time

result_best_RF = []

for i, n in all_data.items():

    line_length = 150
    print('-' * line_length)
    print(f'Baseline датасета: {i}'.center(line_length))
    print('-' * line_length)

    optuna.logging.set_verbosity(optuna.logging.ERROR)
    study = optuna.create_study(direction="minimize")  # ничего лишнего
    study.optimize(partial(objective_RFregresson, data=n), n_trials=15)

    print("Лучшие параметры:", study.best_params)
    print("Лучшее RMSE:", study.best_value)

    result_best_RF.append(study.best_value)
    

all_reault['RF_result'] = result_best_RF

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                          Baseline датасета: crypt_Ethereum
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 184, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt'}
Лучшее RMSE: 126.24668513910166
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                             Baseline датасета: crypt_BTC
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 289, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
Лучшее RMSE: 3394.5723770230043
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                        Baseline датасета: futures_Brent_LCOK5
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 130, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
Лучшее RMSE: 1.762226691542212
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                         Baseline датасета: futures_WTI_CLJ5
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 189, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt'}
Лучшее RMSE: 1.6258108478545645
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                    Baseline датасета: share_metal_jiangxi_copper
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 151, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt'}
Лучшее RMSE: 0.4481392686475207
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                     Baseline датасета: share_metal_baoshan_iron
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 133, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'sqrt'}
Лучшее RMSE: 0.14242221758662008
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: share_oil_petrochina_hk
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 110, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt'}
Лучшее RMSE: 1.268672020554183
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: share_oil_equinor_oslo
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 77, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt'}
Лучшее RMSE: 8.106791595144221
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: spot_preciouse_metal_AG
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 99, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'log2'}
Лучшее RMSE: 1.7409254860977834
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: spot_preciouse_metal_AU
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 124, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'log2'}
Лучшее RMSE: 301.95055545803984
CPU times: user 3min 9s, sys: 2.11 s, total: 3min 11s
Wall time: 1min 4s

In [9]:
def objective_gbr(trial, data):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 300),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 5)
    }

    train_raw, valid_raw, _ = split_data(data)
    tail_len = 30

    train = upgrade_dataset(train_raw)
    valid_with_tail = pd.concat([train_raw.tail(tail_len), valid_raw])
    valid_with_tail = upgrade_dataset(valid_with_tail)
    valid = valid_with_tail.loc[valid_raw.index]

    X_train, y_train = return_x_y(train)
    X_valid, y_valid = return_x_y(valid)

    model = GradientBoostingRegressor(**params)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_valid)

    rmse = np.sqrt(mean_squared_error(y_valid, y_pred))
    return rmse

In [10]:
%%time

result_best_gbr = []

for i, n in all_data.items():

    line_length = 150
    print('-' * line_length)
    print(f'Baseline датасета: {i}'.center(line_length))
    print('-' * line_length)

    optuna.logging.set_verbosity(optuna.logging.ERROR)
    study = optuna.create_study(direction="minimize")  # ничего лишнего
    study.optimize(partial(objective_gbr, data=n), n_trials=15)

    print("Лучшие параметры:", study.best_params)
    print("Лучшее RMSE:", study.best_value)

    result_best_gbr.append(study.best_value)
    

all_reault['GBR_result'] = result_best_gbr

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                          Baseline датасета: crypt_Ethereum
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 239, 'learning_rate': 0.04063717639143676, 'max_depth': 4, 'subsample': 0.6303381907682958, 'min_samples_split': 7, 'min_samples_leaf': 5}
Лучшее RMSE: 120.7240964726063
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                             Baseline датасета: crypt_BTC
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 271, 'learning_rate': 0.11575814816810856, 'max_depth': 3, 'subsample': 0.5834474426183737, 'min_samples_split': 8, 'min_samples_leaf': 4}
Лучшее RMSE: 3064.0707782529093
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                        Baseline датасета: futures_Brent_LCOK5
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 131, 'learning_rate': 0.04657799151285184, 'max_depth': 5, 'subsample': 0.5026939851981022, 'min_samples_split': 10, 'min_samples_leaf': 2}
Лучшее RMSE: 1.6745536206525127
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                         Baseline датасета: futures_WTI_CLJ5
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 297, 'learning_rate': 0.019697172771786824, 'max_depth': 5, 'subsample': 0.9105318359955741, 'min_samples_split': 10, 'min_samples_leaf': 3}
Лучшее RMSE: 1.5038034182582143
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                    Baseline датасета: share_metal_jiangxi_copper
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 259, 'learning_rate': 0.0394105112768372, 'max_depth': 5, 'subsample': 0.552561648631057, 'min_samples_split': 6, 'min_samples_leaf': 4}
Лучшее RMSE: 0.4082486538900867
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                     Baseline датасета: share_metal_baoshan_iron
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 156, 'learning_rate': 0.06267709307510576, 'max_depth': 4, 'subsample': 0.5035597846532046, 'min_samples_split': 6, 'min_samples_leaf': 5}
Лучшее RMSE: 0.1313699687351375
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: share_oil_petrochina_hk
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 252, 'learning_rate': 0.09070313157367105, 'max_depth': 3, 'subsample': 0.96470275080739, 'min_samples_split': 4, 'min_samples_leaf': 1}
Лучшее RMSE: 1.2627377405573084
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: share_oil_equinor_oslo
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 212, 'learning_rate': 0.015617770788890874, 'max_depth': 10, 'subsample': 0.7180495831870386, 'min_samples_split': 9, 'min_samples_leaf': 1}
Лучшее RMSE: 7.27153664994525
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: spot_preciouse_metal_AG
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 115, 'learning_rate': 0.28329965091383236, 'max_depth': 4, 'subsample': 0.8888171211126794, 'min_samples_split': 2, 'min_samples_leaf': 5}
Лучшее RMSE: 1.5246659022497195
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: spot_preciouse_metal_AU
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 245, 'learning_rate': 0.029165495323073845, 'max_depth': 3, 'subsample': 0.6949352371569146, 'min_samples_split': 4, 'min_samples_leaf': 4}
Лучшее RMSE: 299.4297451541091
CPU times: user 17min 36s, sys: 160 ms, total: 17min 37s
Wall time: 17min 37s

In [11]:
def objective_lgbm(trial, data):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 300),
        "learning_rate": trial.suggest_float("learning_rate", 0.005, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "num_leaves": trial.suggest_int("num_leaves", 7, 255),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 30),
        # "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        # "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0)
    }

    train_raw, valid_raw, _ = split_data(data)
    tail_len = 30

    train = upgrade_dataset(train_raw)
    valid_with_tail = pd.concat([train_raw.tail(tail_len), valid_raw])
    valid_with_tail = upgrade_dataset(valid_with_tail)
    valid = valid_with_tail.loc[valid_raw.index]

    X_train, y_train = return_x_y(train)
    X_valid, y_valid = return_x_y(valid)

    model = LGBMRegressor(**params)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_valid)

    rmse = np.sqrt(mean_squared_error(y_valid, y_pred))
    return rmse

In [12]:
%%time

result_best_lgbm = []

for i, n in all_data.items():

    line_length = 150
    print('-' * line_length)
    print(f'Baseline датасета: {i}'.center(line_length))
    print('-' * line_length)

    optuna.logging.set_verbosity(optuna.logging.ERROR)
    study = optuna.create_study(direction="minimize")  # ничего лишнего
    study.optimize(partial(objective_gbr, data=n), n_trials=15)

    print("Лучшие параметры:", study.best_params)
    print("Лучшее RMSE:", study.best_value)

    result_best_lgbm.append(study.best_value)
    

all_reault['LGBM_result'] = result_best_lgbm

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                          Baseline датасета: crypt_Ethereum
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 89, 'learning_rate': 0.14838244465395609, 'max_depth': 4, 'subsample': 0.593966150600739, 'min_samples_split': 6, 'min_samples_leaf': 1}
Лучшее RMSE: 131.56468480609198
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                             Baseline датасета: crypt_BTC
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 263, 'learning_rate': 0.034768918797539045, 'max_depth': 10, 'subsample': 0.6244969377099638, 'min_samples_split': 8, 'min_samples_leaf': 3}
Лучшее RMSE: 3070.375141256699
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                        Baseline датасета: futures_Brent_LCOK5
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 113, 'learning_rate': 0.04168784066713662, 'max_depth': 5, 'subsample': 0.847299685234427, 'min_samples_split': 5, 'min_samples_leaf': 4}
Лучшее RMSE: 1.7256234103260555
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                         Baseline датасета: futures_WTI_CLJ5
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 228, 'learning_rate': 0.02530399074478226, 'max_depth': 3, 'subsample': 0.5186635097435184, 'min_samples_split': 10, 'min_samples_leaf': 4}
Лучшее RMSE: 1.4890142552181462
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                    Baseline датасета: share_metal_jiangxi_copper
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 131, 'learning_rate': 0.08152297836178236, 'max_depth': 3, 'subsample': 0.9105753463898952, 'min_samples_split': 7, 'min_samples_leaf': 2}
Лучшее RMSE: 0.41627326692499833
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                     Baseline датасета: share_metal_baoshan_iron
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 297, 'learning_rate': 0.03099513601768414, 'max_depth': 7, 'subsample': 0.5433818788359892, 'min_samples_split': 4, 'min_samples_leaf': 4}
Лучшее RMSE: 0.1419074493652583
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: share_oil_petrochina_hk
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 235, 'learning_rate': 0.06285259962656568, 'max_depth': 3, 'subsample': 0.5999152942625238, 'min_samples_split': 5, 'min_samples_leaf': 2}
Лучшее RMSE: 1.2485294770613578
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: share_oil_equinor_oslo
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 198, 'learning_rate': 0.01772662146657037, 'max_depth': 5, 'subsample': 0.547998707044669, 'min_samples_split': 10, 'min_samples_leaf': 5}
Лучшее RMSE: 6.973421200254397
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: spot_preciouse_metal_AG
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 204, 'learning_rate': 0.1268403693573627, 'max_depth': 5, 'subsample': 0.9800432421707393, 'min_samples_split': 10, 'min_samples_leaf': 5}
Лучшее RMSE: 1.5498962428366951
------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Baseline датасета: spot_preciouse_metal_AU
------------------------------------------------------------------------------------------------------------------------------------------------------
Лучшие параметры: {'n_estimators': 115, 'learning_rate': 0.09806877494951677, 'max_depth': 3, 'subsample': 0.9694407158555054, 'min_samples_split': 8, 'min_samples_leaf': 3}
Лучшее RMSE: 295.770246263479
CPU times: user 18min 56s, sys: 72.3 ms, total: 18min 56s
Wall time: 18min 56s

In [13]:
all_reault

,dataset_name,dataset_mean_price,RF_result,GBR_result,LGBM_result
0,crypt_Ethereum,1264.224518,126.246685,120.724096,131.564685
1,crypt_BTC,24007.290015,3394.572377,3064.070778,3070.375141
2,futures_Brent_LCOK5,68.036667,1.762227,1.674554,1.725623
3,futures_WTI_CLJ5,63.524965,1.625811,1.503803,1.489014
4,share_metal_jiangxi_copper,10.239784,0.448139,0.408249,0.416273
5,share_metal_baoshan_iron,5.255690,0.142422,0.131370,0.141907
6,share_oil_petrochina_hk,3.622050,1.268672,1.262738,1.248529
7,share_oil_equinor_oslo,187.087574,8.106792,7.271537,6.973421
8,spot_preciouse_metal_AG,20.814301,1.740925,1.524666,1.549896
9,spot_preciouse_metal_AU,1677.948521,301.950555,299.429745,295.770246