# Блок 1. Загрузка данных

## Описание блока:
В данном блоке будет проведена базовая загрузка данных, первичная предобработка типов данных и подготовлена фукнция (в отдельном .py файле) для дальнейшего использования. Подробные выводы и текстовое описание данных будет в основной тетрадке [Открыть тетрадку "Part 0"](Part%200.%20Research%20results.ipynb)

In [1]:
# импорт библиотек
import os
import glob
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

In [2]:
# фиксация сида на будущее
RANDOM_STATE = 654321

In [3]:
# просмотр неймнига данных
csv_files = glob.glob("../data/*/*.csv")  # Ищет все CSV-файлы во вложенных папках
print(csv_files)

['../data/share_oil_gaz_company/equinor_oslo_2016_2024.csv', '../data/share_oil_gaz_company/petrochina_hk_2016_2024.csv', '../data/cryptocurrency/BTC_USD Bitfinex_2016_2024.csv', '../data/cryptocurrency/Ethereum_2016_2024.csv', '../data/share_matal_company/jiangxi_copper_hk_2016_2024.csv', '../data/share_matal_company/baoshan_iron_sh_2016_2024.csv', '../data/futures_market_oil/WTI - Апр 25 (CLJ5) 2016_2024.csv', '../data/futures_market_oil/Brent - Май 25 (LCOK5) 2016_2024.csv', '../data/spot_market_precious_metal/XAU_USD_2016_2024.csv', '../data/spot_market_precious_metal/XAG_USD_2016_2024.csv']

In [4]:
# Создание переменных с датасетами
crypt_Ethereum = pd.read_csv('../data/cryptocurrency/Ethereum_2016_2024.csv')
crypt_BTC = pd.read_csv('../data/cryptocurrency/BTC_USD Bitfinex_2016_2024.csv')

futures_Brent_LCOK5 = pd.read_csv('../data/futures_market_oil/Brent - Май 25 (LCOK5) 2016_2024.csv')
futures_WTI_CLJ5 = pd.read_csv('../data/futures_market_oil/WTI - Апр 25 (CLJ5) 2016_2024.csv')

share_metal_jiangxi_copper = pd.read_csv('../data/share_matal_company/jiangxi_copper_hk_2016_2024.csv')
share_metal_baoshan_iron = pd.read_csv('../data/share_matal_company/baoshan_iron_sh_2016_2024.csv')

share_oil_petrochina_hk = pd.read_csv('../data/share_oil_gaz_company/petrochina_hk_2016_2024.csv')
share_oil_equinor_oslo = pd.read_csv('../data/share_oil_gaz_company/equinor_oslo_2016_2024.csv')

spot_preciouse_metal_AU = pd.read_csv('../data/spot_market_precious_metal/XAU_USD_2016_2024.csv')
spot_preciouse_metal_AG = pd.read_csv('../data/spot_market_precious_metal/XAG_USD_2016_2024.csv')

In [5]:
# компановка датасетов по словарям для будущего упрощения 
# исследования данных

# датасеты крипты
crypt = [
    crypt_Ethereum,
    crypt_BTC
]

# датасеты фючерсов на нефть
fetures = [
    futures_Brent_LCOK5,
    futures_WTI_CLJ5
]

# датасеты акций металург. компаний
share_metal = [
    share_metal_jiangxi_copper,
    share_metal_baoshan_iron
]

# датасеты акций нефтяных компаний
share_oil = [
    share_oil_petrochina_hk,
    share_oil_equinor_oslo
]

# датасеты спотовых цен на драг. металлы 
spot_prec = [
    spot_preciouse_metal_AU,
    spot_preciouse_metal_AG
]

In [6]:
def first_scroll_data(data, name_dataset):
    '''Функция для просмотра базовой информации о
    датасете'''
    line_length = 150
    print('-' * line_length)
    print(f'Обзор датасета: {name_dataset}'.center(line_length))
    print('-' * line_length)


    print('Общая информация:')
    print(data.info())
    print()
    print('Первые пять строк таблицы:')
    display(data.head())
    print()
    print('Последние пять строк таблицы:')
    display(data.tail())

    print()
    print()

In [7]:
def list_scroll(data: list, name_dataset:list):
    '''вторичная функция для прокрутки first_scroll_data 
    используя список'''
    cnt = len(name_dataset)
    number = 0
    for i in data:
        first_scroll_data(i, name_dataset[number])
        number += 1
        print()

### Проверка по группам

In [8]:
list_scroll(crypt, ['crypt_Ethereum', 'crypt_BTC'])

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                            Обзор датасета: crypt_Ethereum
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3293 entries, 0 to 3292
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Дата    3293 non-null   object
 1   Цена    3293 non-null   object
 2   Откр.   3293 non-null   object
 3   Макс.   3293 non-null   object
 4   Мин.    3293 non-null   object
 5   Объём   3285 non-null   object
 6   Изм. %  3293 non-null   object
dtypes: object(7)
memory usage: 180.2+ KB
None

Первые пять строк таблицы:

         Дата      Цена     Откр.     Макс.      Мин.    Объём  Изм. %
0  15.03.2025  1.925,17  1.910,71  1.934,78  1.904,30  318,73K   0,71%
1  14.03.2025  1.911,62  1.863,57  1.945,25  1.861,63  405,34K   2,52%
2  13.03.2025  1.864,69  1.906,05  1.916,35  1.823,72  617,45K  -2,28%
3  12.03.2025  1.908,22  1.923,22  1.955,50  1.833,70  844,66K  -0,73%
4  11.03.2025  1.922,28  1.865,07  1.961,10  1.766,97    1,26M   3,10%

Последние пять строк таблицы:

            Дата   Цена  Откр.  Макс.   Мин.   Объём   Изм. %
3288  14.03.2016  12,50  15,07  15,07  11,40  92,18K  -17,05%
3289  13.03.2016  15,07  12,92  15,07  12,92   1,30K   16,64%
3290  12.03.2016  12,92  11,95  13,45  11,95   0,83K    8,12%
3291  11.03.2016  11,95  11,75  11,95  11,75   0,18K    1,70%
3292  10.03.2016  11,75  11,20  11,85  11,07   0,00K    4,91%

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                              Обзор датасета: crypt_BTC
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3361 entries, 0 to 3360
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Дата    3361 non-null   object
 1   Цена    3361 non-null   object
 2   Откр.   3361 non-null   object
 3   Макс.   3361 non-null   object
 4   Мин.    3361 non-null   object
 5   Объём   3354 non-null   object
 6   Изм. %  3361 non-null   object
dtypes: object(7)
memory usage: 183.9+ KB
None

Первые пять строк таблицы:

         Дата      Цена     Откр.     Макс.      Мин.  Объём  Изм. %
0  15.03.2025  84.497,0  84.207,0  84.911,0  83.832,0  0,75K   0,34%
1  14.03.2025  84.207,0  81.289,0  85.473,0  81.024,0  1,16K   3,59%
2  13.03.2025  81.289,0  83.856,0  84.490,0  80.101,0  0,44K  -3,06%
3  12.03.2025  83.856,0  83.163,0  84.600,0  80.881,0  1,11K   0,86%
4  11.03.2025  83.142,0  78.807,0  83.808,0  77.041,0  1,82K   5,60%

Последние пять строк таблицы:

            Дата   Цена  Откр.  Макс.   Мин.   Объём  Изм. %
3356  05.01.2016  431,8  432,9  434,9  428,2  11,22K  -0,24%
3357  04.01.2016  432,9  428,6  435,7  427,0  13,02K   0,99%
3358  03.01.2016  428,7  432,7  433,1  422,0  19,18K  -0,93%
3359  02.01.2016  432,7  434,0  435,8  430,0   6,38K  -0,29%
3360  01.01.2016  434,0  429,0  436,5  426,3  12,97K   1,16%

Датасеты криптовалюты загружены полностью корректно. Необходимо поправить типы данных.

In [9]:
list_scroll(fetures, ['futures_Brent_LCOK5', 'futures_WTI_CLJ5'])

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                         Обзор датасета: futures_Brent_LCOK5
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2376 entries, 0 to 2375
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Дата    2376 non-null   object
 1   Цена    2376 non-null   object
 2   Откр.   2376 non-null   object
 3   Макс.   2376 non-null   object
 4   Мин.    2376 non-null   object
 5   Объём   2375 non-null   object
 6   Изм. %  2376 non-null   object
dtypes: object(7)
memory usage: 130.1+ KB
None

Первые пять строк таблицы:

         Дата   Цена  Откр.  Макс.   Мин.    Объём  Изм. %
0  14.03.2025  70,58  70,16  70,75  69,93  238,55K   1,00%
1  13.03.2025  69,88  70,95  71,25  69,66  331,69K  -1,51%
2  12.03.2025  70,95  69,95  71,10  69,48  273,31K   2,00%
3  11.03.2025  69,56  69,05  70,44  68,63  282,86K   0,40%
4  10.03.2025  69,28  70,49  70,88  69,05  275,18K  -1,53%

Последние пять строк таблицы:

            Дата   Цена  Откр.  Макс.   Мин.    Объём  Изм. %
2371  08.01.2016  33,55  34,02  34,72  32,78  206,97K  -0,59%
2372  07.01.2016  33,75  34,52  34,74  32,16  291,51K  -1,40%
2373  06.01.2016  34,23  36,64  36,67  34,13  296,86K  -6,01%
2374  05.01.2016  36,42  37,27  37,57  36,24  275,47K  -2,15%
2375  04.01.2016  37,22  37,85  38,99  36,77  321,84K  -0,16%

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                           Обзор датасета: futures_WTI_CLJ5
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2421 entries, 0 to 2420
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Дата    2421 non-null   object
 1   Цена    2421 non-null   object
 2   Откр.   2421 non-null   object
 3   Макс.   2421 non-null   object
 4   Мин.    2421 non-null   object
 5   Объём   2314 non-null   object
 6   Изм. %  2421 non-null   object
dtypes: object(7)
memory usage: 132.5+ KB
None

Первые пять строк таблицы:

         Дата   Цена  Откр.  Макс.   Мин.    Объём  Изм. %
0  14.03.2025  67,18  66,78  67,48  66,59      NaN   0,95%
1  13.03.2025  66,55  67,69  67,94  66,37  268,59K  -1,67%
2  12.03.2025  67,68  66,62  67,88  66,15  246,68K   2,16%
3  11.03.2025  66,25  65,95  67,17  65,29  222,51K   0,33%
4  10.03.2025  66,03  67,11  67,60  65,80  249,63K  -1,51%

Последние пять строк таблицы:

            Дата   Цена  Откр.  Макс.   Мин.    Объём  Изм. %
2416  08.01.2016  33,16  33,30  34,34  32,64  596,50K  -0,33%
2417  07.01.2016  33,27  34,09  34,26  32,10  617,41K  -2,06%
2418  06.01.2016  33,97  36,18  36,39  33,77  563,81K  -5,56%
2419  05.01.2016  35,97  36,90  37,10  35,74  410,13K  -2,15%
2420  04.01.2016  36,76  37,60  38,39  36,33  431,99K  -0,76%

Датасеты фьчерсов на нефть загружены полностью. Есть пустые строчки и необходимо поправить типы данных.

In [10]:
list_scroll(share_metal, ['share_metal_jiangxi_copper', 'share_metal_baoshan_iron'])

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                      Обзор датасета: share_metal_jiangxi_copper
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2284 entries, 0 to 2283
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2284 non-null   object
 1   Close_0358.HK   2284 non-null   float64
 2   High_0358.HK    2284 non-null   float64
 3   Low_0358.HK     2284 non-null   float64
 4   Open_0358.HK    2284 non-null   float64
 5   Volume_0358.HK  2284 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 107.2+ KB
None

Первые пять строк таблицы:

,Date,Close_0358.HK,High_0358.HK,Low_0358.HK,Open_0358.HK,Volume_0358.HK
0,2016-01-04,6.807970,7.213584,6.807970,7.213584,10767005
1,2016-01-05,6.974989,6.998848,6.815924,6.903410,9398911
2,2016-01-06,6.990893,7.030659,6.879547,7.022706,6307590
3,2016-01-07,6.585279,6.959081,6.577326,6.959081,12736729
4,2016-01-08,6.815923,6.839783,6.569373,6.577326,7868251

Последние пять строк таблицы:

,Date,Close_0358.HK,High_0358.HK,Low_0358.HK,Open_0358.HK,Volume_0358.HK
2279,2025-04-07,11.16,12.02,11.12,12.00,67910652
2280,2025-04-08,11.24,11.52,11.10,11.38,27082563
2281,2025-04-09,11.34,11.36,10.72,10.96,30185691
2282,2025-04-10,11.70,11.94,11.64,11.74,28589972
2283,2025-04-11,12.16,12.28,11.72,11.80,31804023

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                       Обзор датасета: share_metal_baoshan_iron
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2250 entries, 0 to 2249
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              2250 non-null   object
 1   Close_600019.SS   2250 non-null   float64
 2   High_600019.SS    2250 non-null   float64
 3   Low_600019.SS     2250 non-null   float64
 4   Open_600019.SS    2250 non-null   float64
 5   Volume_600019.SS  2250 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 105.6+ KB
None

Первые пять строк таблицы:

,Date,Close_600019.SS,High_600019.SS,Low_600019.SS,Open_600019.SS,Volume_600019.SS
0,2016-01-04,3.256845,3.499707,3.244390,3.487252,44732837
1,2016-01-05,3.381389,3.443662,3.207027,3.238163,86707909
2,2016-01-06,3.717659,3.717659,3.356480,3.387616,291901237
3,2016-01-07,3.350253,3.649161,3.344026,3.642933,52582300
4,2016-01-08,3.686525,3.686525,3.431208,3.487253,224377656

Последние пять строк таблицы:

,Date,Close_600019.SS,High_600019.SS,Low_600019.SS,Open_600019.SS,Volume_600019.SS
2245,2025-04-07,6.69,7.11,6.53,7.10,158354652
2246,2025-04-08,6.79,6.87,6.64,6.64,120937178
2247,2025-04-09,6.83,6.83,6.63,6.79,103008747
2248,2025-04-10,6.77,6.90,6.76,6.86,94567843
2249,2025-04-11,6.78,6.80,6.69,6.77,52400674

Датасеты металлургических компаний загружены полностью. Есть пустые строчки и необходимо поправить типы данных.

In [11]:
list_scroll(share_oil, ['share_oil_petrochina_hk', 'share_oil_equinor_oslo'])

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                       Обзор датасета: share_oil_petrochina_hk
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2284 entries, 0 to 2283
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2284 non-null   object
 1   Close_0857.HK   2284 non-null   float64
 2   High_0857.HK    2284 non-null   float64
 3   Low_0857.HK     2284 non-null   float64
 4   Open_0857.HK    2284 non-null   float64
 5   Volume_0857.HK  2284 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 107.2+ KB
None

Первые пять строк таблицы:

,Date,Close_0857.HK,High_0857.HK,Low_0857.HK,Open_0857.HK,Volume_0857.HK
0,2016-01-04,3.286763,3.398068,3.247479,3.365331,90690163
1,2016-01-05,3.234385,3.326047,3.221290,3.260574,89338403
2,2016-01-06,3.195101,3.247479,3.182006,3.208195,105238274
3,2016-01-07,2.985586,3.168911,2.979039,3.136174,191534517
4,2016-01-08,3.064154,3.103438,2.998681,3.037965,101248371

Последние пять строк таблицы:

,Date,Close_0857.HK,High_0857.HK,Low_0857.HK,Open_0857.HK,Volume_0857.HK
2279,2025-04-07,5.32,5.72,5.32,5.50,709630068
2280,2025-04-08,5.47,5.50,5.30,5.30,346718168
2281,2025-04-09,5.20,5.33,5.07,5.28,461769299
2282,2025-04-10,5.24,5.41,5.23,5.37,350832144
2283,2025-04-11,5.28,5.30,5.10,5.20,344810572

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                        Обзор датасета: share_oil_equinor_oslo
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2333 entries, 0 to 2332
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2333 non-null   object
 1   Close_EQNR.OL   2333 non-null   float64
 2   High_EQNR.OL    2333 non-null   float64
 3   Low_EQNR.OL     2333 non-null   float64
 4   Open_EQNR.OL    2333 non-null   float64
 5   Volume_EQNR.OL  2333 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 109.5+ KB
None

Первые пять строк таблицы:

,Date,Close_EQNR.OL,High_EQNR.OL,Low_EQNR.OL,Open_EQNR.OL,Volume_EQNR.OL
0,2016-01-04,84.524803,84.730129,82.403129,84.045717,4108278
1,2016-01-05,82.471573,84.456367,82.471573,84.456367,4158569
2,2016-01-06,80.760521,83.155960,79.733904,83.087520,6404712
3,2016-01-07,78.707275,79.049481,75.353660,78.022864,8884891
4,2016-01-08,75.216820,79.391729,75.011494,79.391729,7992273

Последние пять строк таблицы:

,Date,Close_EQNR.OL,High_EQNR.OL,Low_EQNR.OL,Open_EQNR.OL,Volume_EQNR.OL
2328,2025-04-07,250.500000,256.700012,234.000000,241.000000,4463314
2329,2025-04-08,251.600006,254.699997,246.899994,251.600006,3718667
2330,2025-04-09,237.500000,242.100006,233.600006,240.000000,4826799
2331,2025-04-10,245.000000,252.699997,242.800003,251.500000,3483200
2332,2025-04-11,244.800003,248.000000,242.199997,245.000000,3085771

Датасеты добывающих компаний загружены, есть пустые строчки и необходимо поправить типы данных.

In [12]:
list_scroll(spot_prec, ['spot_preciouse_metal_AU', 'spot_preciouse_metal_AG'])

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                       Обзор датасета: spot_preciouse_metal_AU
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2394 entries, 0 to 2393
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Дата    2394 non-null   object
 1   Цена    2394 non-null   object
 2   Откр.   2394 non-null   object
 3   Макс.   2394 non-null   object
 4   Мин.    2394 non-null   object
 5   Объём   12 non-null     object
 6   Изм. %  2394 non-null   object
dtypes: object(7)
memory usage: 131.1+ KB
None

Первые пять строк таблицы:

         Дата      Цена     Откр.     Макс.      Мин. Объём  Изм. %
0  14.03.2025  2.984,42  2.988,38  3.005,08  2.978,41   NaN  -0,11%
1  13.03.2025  2.987,75  2.932,66  2.989,64  2.932,03   NaN   1,90%
2  12.03.2025  2.932,06  2.916,85  2.940,83  2.906,19   NaN   0,55%
3  11.03.2025  2.916,04  2.888,72  2.922,22  2.880,34   NaN   0,92%
4  10.03.2025  2.889,40  2.912,17  2.918,50  2.880,30   NaN  -0,73%

Последние пять строк таблицы:

            Дата      Цена     Откр.     Макс.      Мин. Объём  Изм. %
2389  07.01.2016  1.109,25  1.094,45  1.110,20  1.091,09   NaN   1,35%
2390  06.01.2016  1.094,45  1.077,55  1.095,45  1.074,70   NaN   1,56%
2391  05.01.2016  1.077,66  1.074,66  1.082,30  1.072,70   NaN   0,28%
2392  04.01.2016  1.074,70  1.065,36  1.083,70  1.061,90   NaN   1,32%
2393  01.01.2016  1.060,74  1.061,21  1.061,41  1.060,74   NaN  -0,05%

------------------------------------------------------------------------------------------------------------------------------------------------------
                                                       Обзор датасета: spot_preciouse_metal_AG
------------------------------------------------------------------------------------------------------------------------------------------------------
Общая информация:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2395 entries, 0 to 2394
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Дата    2395 non-null   object
 1   Цена    2395 non-null   object
 2   Откр.   2395 non-null   object
 3   Макс.   2395 non-null   object
 4   Мин.    2395 non-null   object
 5   Объём   0 non-null      float64
 6   Изм. %  2395 non-null   object
dtypes: float64(1), object(6)
memory usage: 131.1+ KB
None

Первые пять строк таблицы:

         Дата     Цена    Откр.    Макс.     Мин.  Объём  Изм. %
0  14.03.2025  33,7800  33,8130  34,1050  33,5174    NaN  -0,06%
1  13.03.2025  33,8000  33,2530  33,9718  32,9341    NaN   1,72%
2  12.03.2025  33,2300  32,9900  33,3386  32,6984    NaN   0,91%
3  11.03.2025  32,9300  32,1197  33,0150  31,8050    NaN   2,55%
4  10.03.2025  32,1100  32,5350  32,6804  31,9244    NaN  -1,28%

Последние пять строк таблицы:

            Дата     Цена    Откр.    Макс.     Мин.  Объём  Изм. %
2390  07.01.2016  14,3100  14,0000  14,3900  13,9000    NaN   2,14%
2391  06.01.2016  14,0100  13,9500  14,1500  13,8800    NaN   0,21%
2392  05.01.2016  13,9800  13,8500  14,0900  13,7900    NaN   0,72%
2393  04.01.2016  13,8800  13,8200  14,2200  13,7900    NaN   0,51%
2394  01.01.2016  13,8100  13,8500  13,8700  13,7900    NaN  -0,29%

Датасеты драг. металлов загружены, необходимо подправить данные.